 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tv_shows", type: :request do
  # TvShow. As you add validations to TvShow, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TvShow.create! valid_attributes
      get tv_shows_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tv_show = TvShow.create! valid_attributes
      get tv_show_url(tv_show)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tv_show_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tv_show = TvShow.create! valid_attributes
      get edit_tv_show_url(tv_show)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TvShow" do
        expect {
          post tv_shows_url, params: { tv_show: valid_attributes }
        }.to change(TvShow, :count).by(1)
      end

      it "redirects to the created tv_show" do
        post tv_shows_url, params: { tv_show: valid_attributes }
        expect(response).to redirect_to(tv_show_url(TvShow.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TvShow" do
        expect {
          post tv_shows_url, params: { tv_show: invalid_attributes }
        }.to change(TvShow, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tv_shows_url, params: { tv_show: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tv_show" do
        tv_show = TvShow.create! valid_attributes
        patch tv_show_url(tv_show), params: { tv_show: new_attributes }
        tv_show.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tv_show" do
        tv_show = TvShow.create! valid_attributes
        patch tv_show_url(tv_show), params: { tv_show: new_attributes }
        tv_show.reload
        expect(response).to redirect_to(tv_show_url(tv_show))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tv_show = TvShow.create! valid_attributes
        patch tv_show_url(tv_show), params: { tv_show: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tv_show" do
      tv_show = TvShow.create! valid_attributes
      expect {
        delete tv_show_url(tv_show)
      }.to change(TvShow, :count).by(-1)
    end

    it "redirects to the tv_shows list" do
      tv_show = TvShow.create! valid_attributes
      delete tv_show_url(tv_show)
      expect(response).to redirect_to(tv_shows_url)
    end
  end
end
